<?php

declare(strict_types=1);

namespace PhoenixCart\Tests\support;

use PHPUnit\Framework\Assert;
use Symfony\Contracts\HttpClient\HttpClientInterface;

/**
 * Temporary HTTP-shop administrator and admin local configure for storefront acceptance tests.
 */
final class http_admin_fixture {

    public const USERNAME = 'phoenix-http-admin';

    public const PASSWORD = 'phoenix-http-admin';

    public static function login(): HttpClientInterface {
        self::write_admin_local_configure();
        self::ensure_administrator();

        $admin_http = http_bootstrap::client();
        $login_page = $admin_http->request('GET', '/admin/login.php');
        Assert::assertSame(200, $login_page->getStatusCode());

        $login_html = $login_page->getContent(false);
        Assert::assertStringNotContainsString(
            'Create Administrator',
            $login_html,
            'HTTP fixture shop must already have an administrator before login'
        );

        $formid = self::parse_hidden_input($login_html, 'formid');
        Assert::assertNotSame('', $formid);

        $logged_in = $admin_http->request('POST', '/admin/login.php', [
            'query' => ['action' => 'process'],
            'body' => [
                'formid' => $formid,
                'username' => self::USERNAME,
                'password' => self::PASSWORD,
            ],
        ]);
        Assert::assertContains($logged_in->getStatusCode(), [200, 302]);

        $final_url = (string) ($logged_in->getInfo('url') ?? '');
        Assert::assertStringNotContainsString('login.php', $final_url);

        return $admin_http;
    }

    public static function cleanup(): void {
        self::remove_administrator();
        self::remove_admin_local_configure();
    }

    public static function write_admin_local_configure(): void {
        $root = http_bootstrap::catalog_root();
        $local_dir = $root . DIRECTORY_SEPARATOR . 'admin' . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'local';
        if (!is_dir($local_dir) && !mkdir($local_dir, 0775, true) && !is_dir($local_dir)) {
            throw new \RuntimeException('Cannot create admin includes/local: ' . $local_dir);
        }

        $base_url = http_bootstrap::base_url();
        $catalog = self::escape($root);
        $db_server = self::escape(self::env('PHOENIX_DB_HOST', '127.0.0.1'));
        $db_user = self::escape(self::env('PHOENIX_DB_USER', 'phoenix'));
        $db_pass = self::escape(self::env('PHOENIX_DB_PASSWORD', 'phoenix'));
        $db_name = self::escape(self::env('PHOENIX_DB_NAME', 'phoenix_test'));

        $content = <<<PHP
<?php

declare(strict_types=1);

// Generated by phoenix-cart-tests HTTP suite — do not edit by hand.

define('HTTP_SERVER', '{$base_url}');
define('HTTP_CATALOG_SERVER', '{$base_url}');
define('COOKIE_OPTIONS', [
  'lifetime' => 0,
  'domain' => '',
  'path' => '/admin',
  'samesite' => 'Lax',
]);
define('DIR_WS_ADMIN', '/admin/');
define('DIR_WS_CATALOG', '/');
define('DIR_FS_DOCUMENT_ROOT', '{$catalog}/');
define('DIR_FS_ADMIN', '{$catalog}/admin/');
define('DIR_FS_BACKUP', '{$catalog}/admin/backups/');
define('DIR_FS_CATALOG', '{$catalog}/');
define('DIR_FS_SESSION', '');

define('DB_SERVER', '{$db_server}');
define('DB_SERVER_USERNAME', '{$db_user}');
define('DB_SERVER_PASSWORD', '{$db_pass}');
define('DB_DATABASE', '{$db_name}');

PHP;

        $path = $local_dir . DIRECTORY_SEPARATOR . 'configure.php';
        if (file_put_contents($path, $content) === false) {
            throw new \RuntimeException('Failed to write ' . $path);
        }
    }

    public static function remove_admin_local_configure(): void {
        $path = http_bootstrap::catalog_root()
            . DIRECTORY_SEPARATOR . 'admin'
            . DIRECTORY_SEPARATOR . 'includes'
            . DIRECTORY_SEPARATOR . 'local'
            . DIRECTORY_SEPARATOR . 'configure.php';

        if (is_file($path)) {
            unlink($path);
        }
    }

    private static function ensure_administrator(): void {
        mysql_bootstrap::define_connection_constants();
        $mysqli = self::connect();

        $username = self::USERNAME;
        $password_hash = password_hash(self::PASSWORD, PASSWORD_DEFAULT);
        $statement = $mysqli->prepare(
            'INSERT INTO administrators (user_name, user_password) VALUES (?, ?)'
            . ' ON DUPLICATE KEY UPDATE user_password = VALUES(user_password)'
        );
        if ($statement === false) {
            $mysqli->close();
            throw new \RuntimeException('Prepare failed: ' . $mysqli->error);
        }

        $statement->bind_param('ss', $username, $password_hash);
        $statement->execute();
        $statement->close();
        $mysqli->close();
    }

    private static function remove_administrator(): void {
        mysql_bootstrap::define_connection_constants();
        $mysqli = self::connect();

        $username = self::USERNAME;
        $admin = $mysqli->prepare('DELETE FROM administrators WHERE user_name = ?');
        if ($admin === false) {
            $mysqli->close();
            throw new \RuntimeException('Prepare failed: ' . $mysqli->error);
        }
        $admin->bind_param('s', $username);
        $admin->execute();
        $admin->close();

        $recorder = $mysqli->prepare('DELETE FROM action_recorder WHERE user_name = ?');
        if ($recorder === false) {
            $mysqli->close();
            throw new \RuntimeException('Prepare failed: ' . $mysqli->error);
        }
        $recorder->bind_param('s', $username);
        $recorder->execute();
        $recorder->close();
        $mysqli->close();
    }

    private static function connect(): \mysqli {
        $mysqli = new \mysqli(
            (string) DB_SERVER,
            (string) DB_SERVER_USERNAME,
            (string) DB_SERVER_PASSWORD,
            (string) DB_DATABASE
        );

        if ($mysqli->connect_errno) {
            throw new \RuntimeException('MySQL connect failed: ' . $mysqli->connect_error);
        }

        $mysqli->set_charset('utf8mb4');

        return $mysqli;
    }

    private static function parse_hidden_input(string $html, string $name): string {
        $quoted = preg_quote($name, '/');

        if (preg_match('/name="' . $quoted . '"[^>]*\svalue="([^"]*)"/', $html, $matches) === 1) {
            return $matches[1];
        }

        if (preg_match('/value="([^"]*)"[^>]*\sname="' . $quoted . '"/', $html, $matches) === 1) {
            return $matches[1];
        }

        return '';
    }

    private static function env(string $name, string $default): string {
        $value = getenv($name);

        return ($value !== false && $value !== '') ? $value : $default;
    }

    private static function escape(string $value): string {
        return addcslashes($value, "'\\");
    }

}
