<?php

declare(strict_types=1);

namespace PhoenixCart\Tests\Support;

use Symfony\Component\HttpClient\HttpClient;
use Symfony\Contracts\HttpClient\HttpClientInterface;

/**
 * HTTP acceptance shop configure + client factory (wave 4).
 */
final class http_bootstrap
{
    public static function is_enabled(): bool
    {
        $flag = getenv('PHOENIX_HTTP_ENABLED');

        return $flag !== false && $flag !== '' && $flag !== '0';
    }

    public static function base_url(): string
    {
        return rtrim(self::env('PHOENIX_HTTP_BASE_URL', 'http://127.0.0.1:8765'), '/');
    }

    public static function catalog_root(): string
    {
        if (getenv('PHOENIX_CART_ROOT')) {
            return rtrim((string) getenv('PHOENIX_CART_ROOT'), DIRECTORY_SEPARATOR);
        }

        if (defined('DIR_FS_CATALOG')) {
            return rtrim(DIR_FS_CATALOG, DIRECTORY_SEPARATOR . '/');
        }

        throw new \RuntimeException('PHOENIX_CART_ROOT or DIR_FS_CATALOG required for HTTP tests.');
    }

    public static function write_local_configure(): void
    {
        mysql_bootstrap::define_connection_constants();

        $base_url = self::base_url();
        $local_dir = self::catalog_root() . DIRECTORY_SEPARATOR . 'includes' . DIRECTORY_SEPARATOR . 'local';
        if (!is_dir($local_dir) && !mkdir($local_dir, 0775, true) && !is_dir($local_dir)) {
            throw new \RuntimeException('Cannot create catalog includes/local: ' . $local_dir);
        }

        $path = $local_dir . DIRECTORY_SEPARATOR . 'configure.php';
        $db_server = self::escape(self::env('PHOENIX_DB_HOST', '127.0.0.1'));
        $db_user = self::escape(self::env('PHOENIX_DB_USER', 'phoenix'));
        $db_pass = self::escape(self::env('PHOENIX_DB_PASSWORD', 'phoenix'));
        $db_name = self::escape(self::env('PHOENIX_DB_NAME', 'phoenix_test'));

        $content = <<<PHP
<?php

declare(strict_types=1);

// Generated by phoenix-cart-tests HTTP suite — do not edit by hand.

define('HTTP_SERVER', '{$base_url}');
define('COOKIE_OPTIONS', [
  'lifetime' => 0,
  'domain' => '',
  'path' => '/',
  'samesite' => 'Lax',
]);
define('DIR_WS_CATALOG', '/');
define('DIR_FS_CATALOG', dirname(__DIR__, 2) . '/');
define('DIR_FS_SESSION', '');

define('DB_SERVER', '{$db_server}');
define('DB_SERVER_USERNAME', '{$db_user}');
define('DB_SERVER_PASSWORD', '{$db_pass}');
define('DB_DATABASE', '{$db_name}');

PHP;

        if (file_put_contents($path, $content) === false) {
            throw new \RuntimeException('Failed to write ' . $path);
        }
    }

    public static function client(int $max_redirects = 10): HttpClientInterface
    {
        return HttpClient::create([
            'base_uri' => self::base_url(),
            'max_redirects' => $max_redirects,
            'headers' => [
                'User-Agent' => 'phoenix-cart-tests-http/1.0',
            ],
        ]);
    }

    private static function env(string $name, string $default): string
    {
        $value = getenv($name);

        return ($value !== false && $value !== '') ? $value : $default;
    }

    private static function escape(string $value): string
    {
        return addcslashes($value, "'\\");
    }
}
